# Generated by Django 5.1.3 on 2026-01-07 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverpatientrelationship',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_verified',
            new_name='disclaimer_accepted',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='verification_token_created',
            new_name='disclaimer_accepted_at',
        ),
        migrations.RemoveField(
            model_name='caregiverpatientrelationship',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='caregiverpatientrelationship',
            name='request_message',
            field=models.TextField(blank=True, help_text='Message from caregiver explaining relationship'),
        ),
        migrations.AddField(
            model_name='caregiverpatientrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caregiverpatientrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SymptomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_type', models.CharField(choices=[('depressed_mood', 'Depressed Mood'), ('loss_of_interest', 'Loss of Interest or Pleasure'), ('fatigue', 'Fatigue or Loss of Energy'), ('sleep_disturbance', 'Sleep Disturbance (Insomnia/Hypersomnia)'), ('appetite_change', 'Appetite or Weight Change'), ('concentration_difficulty', 'Difficulty Concentrating'), ('feelings_worthlessness', 'Feelings of Worthlessness or Guilt'), ('psychomotor_agitation', 'Psychomotor Agitation or Retardation'), ('suicidal_thoughts', 'Suicidal Thoughts'), ('excessive_worry', 'Excessive Worry'), ('restlessness', 'Restlessness or Feeling On Edge'), ('irritability', 'Irritability'), ('muscle_tension', 'Muscle Tension'), ('panic_attacks', 'Panic Attacks'), ('social_anxiety', 'Social Anxiety'), ('social_withdrawal', 'Social Withdrawal'), ('self_harm', 'Self-Harm Behavior'), ('substance_use', 'Substance Use'), ('mood_swings', 'Mood Swings'), ('headaches', 'Headaches'), ('body_aches', 'Body Aches'), ('digestive_issues', 'Digestive Issues'), ('other', 'Other')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Critical')])),
                ('notes', models.TextField(blank=True, help_text='Additional details about the symptom')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_concerning', models.BooleanField(default=False)),
                ('caregiver_notified', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symptom Record',
                'verbose_name_plural': 'Symptom Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
